config/routes.rb
Staff::Application.routes.draw do
  get 'admin' => 'admin#index'
  get "log_out" => "users#logout", :as => "log_out"
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "pages/home"

  get "pages/help"

  get "pages/contact"

  resources :genders

  resources :titles

  resources :people do
    resources :comments
  end

  resources :salaries
  
  resources :users
  
  get "users/new"
  
  get "sessions/new"
  
  get 'sessions/create'
  
  get 'sessions/my_account'

   root :to => 'pages#home'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :person
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :name
  has_many :people
end

app/models/person.rb
class Person < ActiveRecord::Base
  #attr_accessible :first_name, :surname, :other_names, :dob, :date_of_employment,:date_of_resignation, :salary_id, :email, :telephone, :title_id, :gender_id, :image
  belongs_to :salary
  belongs_to :title
  belongs_to :gender
  has_many :comments, :dependent => :destroy
  
  validates :first_name, :surname, :dob, :date_of_employment, :salary_id, :title_id, :gender_id,  :email, :image, :telephone, :presence => true
  
  validates :telephone, length: {minimum: 10}
  
  validates_format_of :email, :with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i
  
  
  #validate :date_of_employment_date_of_resignation
  mount_uploader :image, ImageUploader
  
  validates :image, allow_blank: false, format: {
with: %r{\.(gif|jpg|png)$}i, message: 'must be a File with GIF, JPG or PNG image.'
}
end

app/models/salary.rb
class Salary < ActiveRecord::Base
  attr_accessible :department, :salary
  has_many :people
end

app/models/title.rb
class Title < ActiveRecord::Base
  attr_accessible :name
  has_many :people
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @users = User.all
    @count = User.all.count
  end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authorize
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authorize
  # GET /people
  # GET /people.json
  def index
    @people = Person.paginate(:page => params[:page], :per_page => 2)


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
    @salary = Salary.all
    @title = Title.all
    @gender = Gender.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
    @salary = Salary.all
    @title = Title.all
    @gender = Gender.all
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])
    @salary = Salary.all
    @title = Title.all
    @gender = Gender.all

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
  
  def search
  @person = Person.find(:all, :conditions => ["surname LIKE ? OR first_name LIKE ? OR salary_id LIKE ?", "%#{params[:key]}%","%#{params[:key]}%","%#{params[:key]}%"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to sessions_new_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to sessions_new_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def logout
    
  session[:user_id] = nil
  
  redirect_to new_user_path , :notice => "Logged out!"
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%=Time.now.strftime("%d/%m/%y %H:%M")%></br>
<p>We have <%= pluralize(@count, "user") %></p>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<a href="log_out">Log out</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Staff</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body bgcolor="#E6E6FA">
<div id="banner">
   <%= image_tag("Logo.jpg", :class => "round") %>
   <%= "Staff Record Application" %>
   </div>
<header>
<table border="2" width="800px" cellpadding = "5" align="center">
<tr>
<th> <%= link_to 'Home', pages_home_path %></th> <th><%= link_to 'Help Center', pages_help_path %></th> <th> <%= link_to 'Admin Contact', pages_contact_path %></th> <th><%= link_to 'Sign in', users_new_path %></th> <th><%= link_to 'log out', pages_home_path %></th></tr>
</tr>
</table><table width="100%"><tr><td align="center">
</header>
<table border="0" width="900"><tr><td align="left">
<section class="round">
<%= yield %>
</section>
</div>
</body>
</html>

app/views/pages/contact.html.erb
<html>
  <p>Call, Email or Fill the form below</p>
<p>Adedayo Bada</p>
<p>NinoSoft Headquaters</p>
<p>Ab24 IWU</p>
<p>deetu02@yahoo.com</p>
<p>Cell - 07534115100</p>
<a target="_blank" href="http://maps.google.co.uk/maps?oe=utf-8&rls=org.mozilla:en-GB:official&client=firefox-a&q=Aberdeen+AB24+1WU,+United+Kingdom&um=1&ie=UTF-8&hq=&hnear=0x48840de2b679d735:0xa9af7ff2c9074e25,Aberdeen+AB24+1WU&gl=uk&ei=vM9eT4mcDIig8gOnzbW6Bw&sa=X&oi=geocode_result&ct=title&resnum=1&ved=0CCEQ8gEwAA">Map Direction</a>
</p>
  <body>
            <fieldset>

               <legend>Personal Details</legend>
            <p>Name: <input type="text" name="name" id="name" /></p>
            
            <p>Email: <input type="text" name="email" id="email" /></p>
            
            <p>Please select your Gender</p>
            <p>
               <input name="status" id="status" type="radio" value="male" /> Male
               <input name="status" id="status" type="radio" value="female" /> Female
            </p>

            </fieldset>
            <fieldset>
               <legend>Message</legend>
                
            <p>Comment:</p>

            <textarea name="message" id="message" rows="6" cols="40"> No comment... </textarea>
            </textarea>
            <p>
               
               <input type="submit" value="Submit your Feedback"/>
               <input type="reset" value="Clear the form"/>
            </p>
		</fieldset>
            <input type="hidden" name="username" id="username" value="t05aab11"/>

            <input type="hidden" name="webmastermail" id="webmastermail" value="adedayo.bada.11@abdn.ac.uk"/>
            <input type="hidden" name="homepage" id="homepage" value="www.abdn.ac.uk/~t05aab11/"/>
         </form>

      
   </body> 
</html

app/views/pages/home.html.erb
<table width="100%"><tr><td align="center">

<%= image_tag("Official.jpg", :class => "round") %>

</table>
<p>NinoSoft INC. specializes in customer aquisition and loyalty through
Website design, Website Application Software development and Office Computer Network designs & Implimentation.

We strive to offer you cutting-edge design and marketing solutions to take your Business to new levels.</p>

<p>Our professional programming and staff will ensure superior website design and functionality
to meet all your business needs.

Combined with our expert marketing staff, we will ensure your business the tools and capabilities to reach new customers and increase sales!!!</p>

<p>Let us help you discover new and exciting ways to manage your staff today...
</p>