config/routes.rb
Staff::Application.routes.draw do
  get 'admin' => 'admin#index'
  get "log_out" => "users#logout", :as => "log_out"
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "pages/home"

  get "pages/help"

  get "pages/contact"

  resources :genders

  resources :titles

  resources :people do
    resources :comments
  end

  resources :salaries
  
  resources :users
  
  get "users/new"
  
  get "sessions/new"
  
  get 'sessions/create'
  
  get 'sessions/my_account'

   root :to => 'pages#home'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/salary.rb
class Salary < ActiveRecord::Base
  attr_accessible :department, :salary
  has_many :people
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  # GET /salaries
  # GET /salaries.json
  def index
    @salaries = Salary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @salaries }
    end
  end

  # GET /salaries/1
  # GET /salaries/1.json
  def show
    @salary = Salary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @salary }
    end
  end

  # GET /salaries/new
  # GET /salaries/new.json
  def new
    @salary = Salary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @salary }
    end
  end

  # GET /salaries/1/edit
  def edit
    @salary = Salary.find(params[:id])
  end

  # POST /salaries
  # POST /salaries.json
  def create
    @salary = Salary.new(params[:salary])

    respond_to do |format|
      if @salary.save
        format.html { redirect_to @salary, notice: 'Salary was successfully created.' }
        format.json { render json: @salary, status: :created, location: @salary }
      else
        format.html { render action: "new" }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /salaries/1
  # PUT /salaries/1.json
  def update
    @salary = Salary.find(params[:id])

    respond_to do |format|
      if @salary.update_attributes(params[:salary])
        format.html { redirect_to @salary, notice: 'Salary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @salary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salaries/1
  # DELETE /salaries/1.json
  def destroy
    @salary = Salary.find(params[:id])
    @salary.destroy

    respond_to do |format|
      format.html { redirect_to salaries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/_form.html.erb
<%= form_for(@salary) do |f| %>
  <% if @salary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salary.errors.count, "error") %> prohibited this salary from being saved:</h2>

      <ul>
      <% @salary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.number_field :salary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salaries/edit.html.erb
<h1>Editing salary</h1>

<%= render 'form' %>

<%= link_to 'Show', @salary %> |
<%= link_to 'Back', salaries_path %>

app/views/salaries/index.html.erb
<h1>Listing salaries</h1>

<table>
  <tr>
    <th>Department</th>
    <th>Salary</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @salaries.each do |salary| %>
  <tr>
    <td><%= salary.department %></td>
    <td><%= salary.salary %></td>
    <td><%= link_to 'Show', salary %></td>
    <td><%= link_to 'Edit', edit_salary_path(salary) %></td>
    <td><%= link_to 'Destroy', salary, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Salary', new_salary_path %>

app/views/salaries/new.html.erb
<h1>New salary</h1>

<%= render 'form' %>

<%= link_to 'Back', salaries_path %>

app/views/salaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Department:</b>
  <%= @salary.department %>
</p>

<p>
  <b>Salary:</b>
  <%= @salary.salary %>
</p>


<%= link_to 'Edit', edit_salary_path(@salary) %> |
<%= link_to 'Back', salaries_path %>